server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.springframework : DEBUG

  mail:
    host: localhost
    port: 2525
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls.enable: false

jwt:
  secret: MaSuperClefSecreteTrèsLonguePourHmacSha256DontTuDoisPrendreSoin1234567890
  expiration: 3600000

app:
  frontend:
    reset-password-url: "http://localhost:4200/reset-password?token="
