server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://jdrbibli-db:3306/auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 30000   # 30s avant d'abandonner
      maximum-pool-size: 10
      minimum-idle: 1
      validation-timeout: 5000    # 5s pour tester la connexion
      initialization-fail-timeout: -1  # NE PAS échouer si la DB n'est pas prête au démarrage

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  flyway:
    enabled: false
    locations: classpath:db/migration

logging:
  level:
    org.springframework: DEBUG
    com.jdrbibli: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: TRACE
    org.springframework.web.servlet.DispatcherServlet: TRACE

mail:
  host: localhost
  port: 25
  username: ""
  password: ""
  properties:
    mail:
      smtp:
        auth: false
        starttls.enable: false

jwt:
  secret: Z2dKbnRHY0NvcnNDWUR0bFhHZ3R3NzIzbVRZT3o0Sk5GZjBWT2tVdzBrckxKVXphMnJKZThCb21BZzk1OU9sWkQ=

  expiration: 3600000

app:
  frontend:
    reset-password-url: "http://localhost:4200/reset-password?token="
  user-service-url: http://user-service:8082/api/users
  audit-url: http://audit-service:8085/api/audit/logs

