# Définition des volumes pour persister les données
volumes:
  jdrbibli_db_data:
  mongo_data:

services:
  mariadb:
    container_name: jdrbibli-db
    image: mariadb:11.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jdrbibli
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306" # Port externe pour accès depuis l'hôte
    volumes:
      - ./docker/db-init:/docker-entrypoint-initdb.d
      - jdrbibli_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "true"]
      interval: 300s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - jdrbibli-network

  mongodb:
    container_name: jdrbibli-mongo
    image: mongo:7
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./docker/mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 300s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - jdrbibli-network

  auth-service:
    container_name: jdrbibli-auth-service
    build:
      context: ./auth-service
    ports:
      - "8081:8081"
    depends_on:
      - mariadb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://auth-service:8081/actuator/health"]
      interval: 3000s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - jdrbibli-network

  user-service:
    container_name: jdrbibli-user-service
    build:
      context: ./user-service
    ports:
      - "8082:8082"
    depends_on:
      - auth-service
      - mariadb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://user-service:8082/actuator/health"]
      interval: 300s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - jdrbibli-network

  ouvrage-service:
    container_name: jdrbibli-ouvrage-service
    build:
      context: ./ouvrage-service
    ports:
      - "8083:8083"
    depends_on:
      - auth-service
      - mariadb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://ouvrage-service:8083/actuator/health"]
      interval: 300s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - jdrbibli-network

  audit-service:
    container_name: jdrbibli-audit-service
    build:
      context: ./audit-service
    ports:
      - "8085:8085"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://jdrbibli-mongo:27017/auditdb
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://audit-service:8085/actuator/health || exit 0",
        ]
      interval: 300s
      timeout: 5s
      retries: 10
      start_period: 90s
    networks:
      - jdrbibli-network

  gateway:
    container_name: jdrbibli-gateway
    build:
      context: ./gateway
    ports:
      - "8084:8084"
    depends_on:
      - auth-service
      - user-service
      - ouvrage-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://gateway:8084/actuator/health"]
      interval: 300s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - jdrbibli-network

  jdrbibli-frontend:
    container_name: jdrbibli-frontend
    build:
      context: ./jdrbibli-frontend
    ports:
      - "4200:80"
    depends_on:
      - gateway
    networks:
      - jdrbibli-network

  jdrbibli-phpmyadmin:
    container_name: jdrbibli-phpmyadmin
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - jdrbibli-network

  # portainer (commenté pour l'instant, à décommenter si nécessaire)
  # portainer:
  #   container_name: jdrbibli-portainer
  #   image: portainer/portainer-ce:latest
  #   restart: always
  #   ports:
  #     - "9443:9443"
  #     - "9000:9000"  # pour l'UI classique
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer_data:/data
  #   networks:
  #     - jdrbibli-network

# Définition du réseau Docker
networks:
  jdrbibli-network:
    driver: bridge
