volumes:
  jdrbibli_db_data:
  mongo_data:

services:
  mariadb:
    image: mariadb:11.4
    container_name: jdrbibli-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jdrbibli
    ports:
      - "3307:3306" # port externe pour accès depuis l'hôte
    volumes:
      - ./docker/db-init:/docker-entrypoint-initdb.d
      - jdrbibli_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "true"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  mongodb:
    image: mongo:7
    container_name: jdrbibli-mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./docker/mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8081:8081"
    depends_on:
      - mariadb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  user-service:
    build:
      context: ./user-service
    ports:
      - "8082:8082"
    depends_on:
      - auth-service
      - mariadb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  ouvrage-service:
    build:
      context: ./ouvrage-service
    ports:
      - "8083:8083"
    depends_on:
      - auth-service
      - mariadb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  audit-service:
    build:
      context: ./audit-service
    ports:
      - "8085:8085"
    depends_on:
    - mongodb
    environment:
    - SPRING_DATA_MONGODB_URI=mongodb://jdrbibli-mongo:27017/auditdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  gateway:
    build:
      context: ./gateway
    ports:
      - "8084:8084"
    depends_on:
      - auth-service
      - user-service
      - ouvrage-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  jdrbibli-frontend:
    build:
      context: ./jdrbibli-frontend
    ports:
      - "4200:80"
    depends_on:
      - gateway

  jdrbibli-phpmyadmin:
    image: phpmyadmin:latest
    container_name: jdrbibli-phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mariadb
