server:
  port: 8084

spring:
  application:
    name: gateway

  webflux:
    cors:
      allowed-origins: "http://localhost:4200"  # Frontend Angular local
      allowed-methods: "*"
      allowed-headers: "*"
      exposed-headers: "Authorization"
      allow-credentials: true

  cloud:
    gateway:
      default-filters:
        - name: DedupeResponseHeader
          args:
            name: Access-Control-Allow-Origin
            strategy: RETAIN_FIRST
        - name: DedupeResponseHeader
          args:
            name: Access-Control-Allow-Credentials
            strategy: RETAIN_FIRST
      routes:
        # -------------------------
        # Auth Service
        # -------------------------
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        # -------------------------
        # User Service
        # -------------------------
        - id: user-service
          uri: http://user-service:8082
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        # -------------------------
        # Friends (User) Service
        # -------------------------
        - id: user-service-friends
          uri: http://user-service:8082
          predicates:
            - Path=/api/friends/**
          filters:
            - StripPrefix=1

        # -------------------------
        # Ouvrage Service
        # -------------------------
        - id: ouvrage-service
          uri: http://ouvrage-service:8083
          predicates:
            - Path=/api/ouvrages/**
          filters:
            - StripPrefix=1

        # -------------------------
        # Audit Service
        # -------------------------
        - id: audit-service
          uri: http://audit-service:8085
          predicates:
            - Path=/api/audit/**
          filters:
            - StripPrefix=1

        # -------------------------
        # Actuator (Gateway itself)
        # -------------------------
        - id: actuator
          uri: http://gateway:8084
          predicates:
            - Path=/actuator/**

jwt:
  secret: Z2dKbnRHY0NvcnNDWUR0bFhHZ3R3NzIzbVRZT3o0Sk5GZjBWT2tVdzBrckxKVXphMnJKZThCb21BZzk1OU9sWkQ=

management:
  endpoint:
    gateway:
      enabled: true     # <--- Active explicitement l’endpoint
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, gateway

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.springframework.cloud.gateway: DEBUG
