server:
  port: 8084

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/** # on prend tout ce qui commence par /api/auth/
          filters:
            - StripPrefix=1 # enlève le "api" → il reste /auth/**

        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
          filters:
          #  - StripPrefix=1

        - id: ouvrage-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/ouvrage/**
          filters:
            - StripPrefix=0

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
