server:
  port: 8084

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        - id: ouvrage-service
          uri: http://localhost:8083
          predicates:
            - Path=/ouvrage/**
          filters:
            - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
