### Obtenir la liste de tous les utilisateurs
GET http://localhost:8084/user/api/users
Accept: application/json

###

### Obtenir un utilisateur par ID
GET http://localhost:8084/user/api/users/1
Accept: application/json

###

### Créer un nouvel utilisateur
POST http://localhost:8084/user/api/users
Content-Type: application/json

{
  "pseudo": "vincent",
  "email": "vincent@example.com",
  "avatarUrl": "/uploads/avatars/default.png"
}

###

### Supprimer un utilisateur par ID
DELETE http://localhost:8084/user/api/users/4

###

### Uploader un avatar pour un utilisateur
# Remplace "vincent" par le username à tester
POST http://localhost:8084/user/api/users/dede/avatar
Content-Type: multipart/form-data

--boundary
Content-Disposition: form-data; name="file"; filename="avatar.png"
Content-Type: image/png

< ./avatar.png
--boundary--
