spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

server:
  port: 8082
