### Connexion (pour récupérer le JWT)
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "pseudo": "vincent",
  "password": "T@u1234567890"
}



### Test modification du mot de passe
PUT http://localhost:8084/auth/profile/password
Content-Type: application/json
Authorization: Bearer {{eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2aW5jZW50IiwiaWF0IjoxNzUyODYxMjM0LCJleHAiOjE3NTI4NjQ4MzR9.__J_pi0TMU_4-ZVba4E28ZEk0oGdMwbEIPdmvfwuN-A}}

{
  "currentPassword": "T@u1234567890",
  "newPassword": "T@u123456789",
  "confirmNewPassword": "T@u123456789"
}
