server:
  port: 8083

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/ouvrage_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: S&qr1t&
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  flyway:
    enabled: false
    locations: classpath:db/migration




logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.flywaydb: DEBUG
