### Liste toutes les gammes
GET http://localhost:8083/api/gammes
Accept: application/json

### Création d'une gamme
POST http://localhost:8083/api/gammes
Content-Type: application/json

{
  "nom": "Donjons & Dragonsxxxxx",
  "description": "La gamme de base de Donjons & Dragons"
}

### Récupérer une gamme par ID (remplacer 1 par l'id réel)
GET http://localhost:8083/api/gammes/6
Accept: application/json

### Mettre à jour une gamme (remplacer 1 par l'id réel)
PUT http://localhost:8083/api/gammes/6
Content-Type: application/json

{
  "nom": "Donjons & Dragons (édition mise à jour)",
  "description": "Description mise à jour de la gamme D&D"
}

### Supprimer une gamme sans force (devrait échouer si gamme non vide)
DELETE http://localhost:8083/api/gammes/6

### Supprimer une gamme avec force (supprime aussi les ouvrages liés)
DELETE http://localhost:8083/api/gammes/11?force=true

####

GET http://localhost:8084/api/ouvrage/ouvrages/gammes/43
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYWEiLCJpYXQiOjE3NTc5NDA3MDIsImV4cCI6MTc1Nzk0NDMwMn0.aefo_y-lfL8C_1SozO6uAdbc7XiMbkVi--HUzZMwK9U
X-User-Pseudo: aaa
Accept: application/json

###

GET http://localhost:8083/api/ouvrage/ouvrages/gammes/43
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYWEiLCJpYXQiOjE3NTc5NDA3MDIsImV4cCI6MTc1Nzk0NDMwMn0.aefo_y-lfL8C_1SozO6uAdbc7XiMbkVi--HUzZMwK9U
X-User-Pseudo: aaa
Accept: application/json

#########
### Récupérer un ouvrage par son ID
GET http://localhost:8083/api/ouvrage/ouvrages/78
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MTk2LCJzdWIiOiJiY2QiLCJpYXQiOjE3NTgzMDc4MzYsImV4cCI6MTc1ODMxMTQzNn0.QknjyEiRYV5wGeeHCxCSo06D78nLqPjL_Qa1Wme0_pU
X-User-Id: 196

### Créer un nouvel ouvrage avec liens médias
POST http://localhost:8083/api/ouvrage/ouvrages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MTk2LCJzdWIiOiJiY2QiLCJpYXQiOjE3NTgzMDc4MzYsImV4cCI6MTc1ODMxMTQzNn0.QknjyEiRYV5wGeeHCxCSo06D78nLqPjL_Qa1Wme0_pU
X-User-Id: 196

{
  "titre": "ouvrageTestMedia",
  "description": "Test sauvegarde liens médias",
  "gammeId": 75,
  "version": "1.0",
  "typeOuvrage": "Livre papier",
  "datePublication": "2025-09-19",
  "langue": "Français",
  "editeur": "ÉditeurTest",
  "etat": "Bon",
  "isbn": "1234567890",
  "pret": true,

  "scenariosContenus": ["Scenario1", "Scenario2"],
  "autresOuvragesGamme": [],
  "imageUrl": "/uploads/images/test.jpg"
}



